spring:
  application:
    name: api-gateway
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      fail-fast: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
