spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/spendwise}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service-route
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/users/**
            - id: transaction-service-route
              uri: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/transactions/**


server:
  port: ${GATEWAY_SERVER_PORT:8088}

spendwise:
  services:
    user:
      url: ${USER_SERVICE_URL:http://localhost:8081}
    transaction:
      url: ${TRANSACTION_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: SpendWise Gateway
    description: API Gateway for SpendWise microservices
    version: 1.0.0