spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/auth_db
    username: ${DB_USERNAME:spendwise}
    password: ${DB_PASSWORD:spendwise}
  flyway:
    enabled: true

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db
